name: publish
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: modrinth release
        run: ./gradlew modrinth -Pchangelog="$(gh release view --json body -q .body)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./build/libs/*.jar
          file_glob: true
          overwrite: true